name: optidice
dependencies:
- python=3.6
- cudatoolkit=10.1
- cudnn=7
- numpy<1.19
- tqdm
- cython
- patchelf  # for mujoco_py
- pip
- pip:
  - tensorflow-gpu==2.3.1
  - tensorflow-probability==0.11.1
  - tf-agents==0.6.0
  - gym==0.17.3
  - pyglib==0.1
  - mujoco_py==1.50.1.68
  - pyparsing==2.4.7
